/*
===============================================================================
Script:         04_analyze_dimensions.sql
Purpose:        Analyze customers, products, and sales across key dimensions.

Analysis Areas:
    - Customers by country
    - Customers by gender
    - Products by category
    - Average product cost by category
    - Sales by product category
    - Sales by customer
    - Quantity sold by country

Business Questions:
    - How are customers distributed across countries?
    - How are customers distributed by gender?
    - How many products belong to each category?
    - What is the average product cost by category?
    - Which product categories generate the most sales?
    - Which customers generate the most revenue?
    - Which countries purchase the highest quantity of products?

Source Views:
    - gold.dim_customers
    - gold.dim_products
    - gold.fact_sales

Notes:
    LEFT JOIN is used when combining the fact table with dimensions so that
    sales records are retained even if a corresponding dimension record
    cannot be found.

===============================================================================
*/


/*
===============================================================================
1. Customer Distribution by Country

Purpose:
    Count the number of customers in each country.

Business Use:
    Understand the geographic distribution of the customer base.

===============================================================================
*/

SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY
    country
ORDER BY
    total_customers DESC;


/*
===============================================================================
2. Customer Distribution by Gender

Purpose:
    Count the number of customers in each gender category.

Business Use:
    Understand the demographic composition of the customer base.

===============================================================================
*/

SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY
    gender
ORDER BY
    total_customers DESC;


/*
===============================================================================
3. Product Count by Category

Purpose:
    Count the number of products available in each category.

Business Use:
    Understand the size and composition of the product catalog.

===============================================================================
*/

SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY
    category
ORDER BY
    total_products DESC;


/*
===============================================================================
4. Average Product Cost by Category

Purpose:
    Calculate the average product cost for each category.

Business Use:
    Compare the typical cost structure across product categories.

===============================================================================
*/

SELECT
    category,
    AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY
    category
ORDER BY
    average_cost DESC;


/*
===============================================================================
5. Sales by Product Category

Purpose:
    Calculate total sales generated by each product category.

Business Use:
    Identify categories contributing the most revenue.

===============================================================================
*/

SELECT
    p.category,
    SUM(s.sales) AS total_sales
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
    ON p.product_key = s.product_key
GROUP BY
    p.category
ORDER BY
    total_sales DESC;


/*
===============================================================================
6. Sales by Customer

Purpose:
    Calculate the total revenue generated by each customer.

Business Use:
    Identify high-value customers and understand customer-level
    revenue contribution.

===============================================================================
*/

SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales) AS total_sales
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = s.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY
    total_sales DESC;


/*
===============================================================================
7. Quantity Sold by Country

Purpose:
    Calculate the total quantity purchased by customers in each country.

Business Use:
    Compare sales volume across geographic markets.

Note:
    This measures quantity sold, not revenue. A country with higher quantity
    does not necessarily generate higher sales because product prices can vary.

===============================================================================
*/

SELECT
    c.country,
    SUM(s.quantity) AS total_quantity
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = s.customer_key
GROUP BY
    c.country
ORDER BY
    total_quantity DESC;


/*
===============================================================================
Key Takeaways
===============================================================================

1. CUSTOMER ANALYSIS
   - Country distribution
   - Gender distribution
   - Customer-level revenue

2. PRODUCT ANALYSIS
   - Product count by category
   - Average product cost by category

3. SALES ANALYSIS
   - Revenue by product category
   - Quantity sold by country

4. DIMENSIONAL ANALYSIS
   Fact-to-dimension joins allow sales metrics to be analyzed from different
   business perspectives such as customer, product, and geography.

5. IMPORTANT DISTINCTION
   Revenue and quantity measure different aspects of performance.

       SUM(sales)    → monetary value generated
       SUM(quantity) → number of units sold

   Therefore, the country or category with the highest quantity may not
   necessarily have the highest revenue.

===============================================================================
*/
